"classes/ClassTipsList.res"
{
"ClassTipsListPanel"
{
"ControlName""PanelListPanel"
"fieldName""ClassTipsListPanel"
"xpos""0"
"ypos""0"
"wide""355"
"tall""225"
"autoResize""3"
"pinCorner""1"
"visible""1"
"enabled""1"
"bgcolor_override""Nada"
"border""Null"
}
}