"Resource/UI/ControlPointCountdown.res"
{
"CapCountdownLabel"
{
"ControlName""CExLabel"
"fieldName""CapCountdownLabel"
"font""CustomAmmoFontReserv"
"xpos""0"
"ypos""0"
"zpos""1"
"wide""30"
"tall""30"
"visible""1"
"enabled""1"
"labelText""%capturetime%"
"textAlignment""center"
"fgcolor""1_disabledFgColor_override"
"bgcolor""TanLight"
}
}
