
"Resource/UI/HudDamageAccount.res"
{
"DamageAccountValue"
{
"xpos_minmode""c190"
"ypos_minmode""c130"
"wide_minmode""100"
"tall_minmode""36"
"font_minmode""CustomDmgFontMinmode"
"border_minmode""Null"
}
"DamageAccountValueShadow"
{
"wide_minmode""100"
"tall_minmode""36"
"font_minmode""CustomDmgFontMinmode"
}
}